//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_recibos
    {
        public string auto { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string auto_usuario { get; set; }
        public decimal importe { get; set; }
        public string usuario { get; set; }
        public decimal monto_recibido { get; set; }
        public string cobrador { get; set; }
        public string auto_cliente { get; set; }
        public string cliente { get; set; }
        public string ci_rif { get; set; }
        public string codigo { get; set; }
        public string estatus_anulado { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string auto_cobrador { get; set; }
        public decimal anticipos { get; set; }
        public decimal cambio { get; set; }
        public string nota { get; set; }
        public string codigo_cobrador { get; set; }
        public string auto_cxc { get; set; }
        public decimal retenciones { get; set; }
        public decimal descuentos { get; set; }
        public string hora { get; set; }
        public string cierre { get; set; }
        public string cierre_ftp { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual cxc cxc { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual empresa_cobradores empresa_cobradores { get; set; }
    }
}
