//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_configuracion
    {
        public int id { get; set; }
        public string idSucursal { get; set; }
        public string idDeposito { get; set; }
        public string idVendedor { get; set; }
        public string idCobrador { get; set; }
        public string idTransporte { get; set; }
        public string idMedioPagoEfectivo { get; set; }
        public string idMedioPagoDivisa { get; set; }
        public string idMedioPagoOtros { get; set; }
        public string idClaveUsar { get; set; }
        public string idPrecioManejar { get; set; }
        public string idConceptoVenta { get; set; }
        public string idConceptoDevVenta { get; set; }
        public string idConceptoSalida { get; set; }
        public string idMedioPagoElectronico { get; set; }
        public string validarExistencia { get; set; }
        public string idTipoDocVenta { get; set; }
        public string idTipoDocDevVenta { get; set; }
        public string idTipoDocNotaEntrega { get; set; }
        public string idSerieFactura { get; set; }
        public string idSerieNotaCredito { get; set; }
        public string idSerieNotaEntrega { get; set; }
        public string idSerieNotaDebito { get; set; }
        public string activar_busqueda_descripcion { get; set; }
        public string activar_repesaje { get; set; }
        public decimal limite_inferior_repesaje { get; set; }
        public decimal limite_superior_repesaje { get; set; }
        public string modoPrecio { get; set; }
        public string estatus { get; set; }
    }
}
