//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_pendiente
    {
        public int id { get; set; }
        public int id_p_operador { get; set; }
        public string auto_cliente { get; set; }
        public string cirif_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public System.DateTime feche { get; set; }
        public string hora { get; set; }
        public decimal monto { get; set; }
        public decimal monto_divisa { get; set; }
        public int renglones { get; set; }
    
        public virtual p_operador p_operador { get; set; }
    }
}
