//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_resumen
    {
        public int id { get; set; }
        public int id_p_operador { get; set; }
        public decimal m_efectivo { get; set; }
        public int cnt_efectivo { get; set; }
        public decimal m_divisa { get; set; }
        public int cnt_divisa { get; set; }
        public decimal m_electronico { get; set; }
        public int cnt_electronico { get; set; }
        public decimal m_otros { get; set; }
        public int cnt_otros { get; set; }
        public decimal m_devolucion { get; set; }
        public int cnt_devolucion { get; set; }
        public decimal m_contado { get; set; }
        public decimal m_credito { get; set; }
        public int cnt_doc { get; set; }
        public int cnt_fac { get; set; }
        public int cnt_ncr { get; set; }
        public decimal m_fac { get; set; }
        public decimal m_ncr { get; set; }
        public int cnt_doc_contado { get; set; }
        public int cnt_doc_credito { get; set; }
        public decimal m_nte { get; set; }
        public int cnt_nte { get; set; }
        public decimal m_anu { get; set; }
        public int cnt_anu { get; set; }
        public decimal m_anu_nte { get; set; }
        public int cnt_anu_nte { get; set; }
        public decimal m_anu_ncr { get; set; }
        public int cnt_anu_ncr { get; set; }
        public decimal m_anu_fac { get; set; }
        public int cnt_anu_fac { get; set; }
        public int cnt_cambio { get; set; }
        public decimal m_cambio { get; set; }
        public int cnt_doc_contado_anulado { get; set; }
        public int cnt_doc_credito_anulado { get; set; }
        public decimal m_contado_anulado { get; set; }
        public decimal m_credito_anulado { get; set; }
        public int cnt_efectivo_anulado { get; set; }
        public decimal m_efectivo_anulado { get; set; }
        public int cnt_divisa_anulado { get; set; }
        public decimal m_divisa_aunlado { get; set; }
        public int cnt_electronico_anulado { get; set; }
        public decimal m_electronico_anulado { get; set; }
        public int cnt_otros_anulado { get; set; }
        public decimal m_otros_anulado { get; set; }
        public int cnt_cambio_anulado { get; set; }
        public decimal m_cambio_anulado { get; set; }
        public string auto_pos_arqueo { get; set; }
    
        public virtual p_operador p_operador { get; set; }
    }
}
