//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_arqueo
    {
        public string auto_cierre { get; set; }
        public string auto_usuario { get; set; }
        public string codigo { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public decimal diferencia { get; set; }
        public decimal efectivo { get; set; }
        public decimal cheque { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal ticket { get; set; }
        public decimal firma { get; set; }
        public decimal retiro { get; set; }
        public decimal otros { get; set; }
        public decimal devolucion { get; set; }
        public decimal subtotal { get; set; }
        public decimal cobranza { get; set; }
        public decimal total { get; set; }
        public decimal mefectivo { get; set; }
        public decimal mcheque { get; set; }
        public decimal mbanco1 { get; set; }
        public decimal mbanco2 { get; set; }
        public decimal mbanco3 { get; set; }
        public decimal mbanco4 { get; set; }
        public decimal mtarjeta { get; set; }
        public decimal mticket { get; set; }
        public decimal mtrans { get; set; }
        public decimal mfirma { get; set; }
        public decimal motros { get; set; }
        public decimal mgastos { get; set; }
        public decimal mretiro { get; set; }
        public decimal mretenciones { get; set; }
        public decimal msubtotal { get; set; }
        public decimal mtotal { get; set; }
        public string cierre_ftp { get; set; }
        public int cnt_divisa { get; set; }
        public int cnt_divisa_usuario { get; set; }
        public int cntDoc { get; set; }
        public int cntDocFac { get; set; }
        public int cntDocNcr { get; set; }
        public decimal montoFac { get; set; }
        public decimal montoNcr { get; set; }
    }
}
