//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_deposito
    {
        public string auto_producto { get; set; }
        public string auto_deposito { get; set; }
        public decimal fisica { get; set; }
        public decimal reservada { get; set; }
        public decimal disponible { get; set; }
        public string ubicacion_1 { get; set; }
        public string ubicacion_2 { get; set; }
        public string ubicacion_3 { get; set; }
        public string ubicacion_4 { get; set; }
        public decimal nivel_minimo { get; set; }
        public decimal pto_pedido { get; set; }
        public decimal nivel_optimo { get; set; }
        public System.DateTime fecha_conteo { get; set; }
        public decimal resultado_conteo { get; set; }
        public decimal averia { get; set; }
    
        public virtual empresa_depositos empresa_depositos { get; set; }
        public virtual productos productos { get; set; }
    }
}
