//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema_configuracion
    {
        public string codigo { get; set; }
        public string operacion { get; set; }
        public string valor { get; set; }
        public string defecto { get; set; }
        public string usuario { get; set; }
        public string tipo { get; set; }
        public string modulo { get; set; }
    }
}
