//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityPos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendedores()
        {
            this.clientes = new HashSet<clientes>();
            this.cxc = new HashSet<cxc>();
            this.ventas_detalle = new HashSet<ventas_detalle>();
            this.ventas = new HashSet<ventas>();
        }
    
        public string auto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string ci { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public System.DateTime fecha_baja { get; set; }
        public string memo { get; set; }
        public string advertencia { get; set; }
        public string estatus { get; set; }
        public decimal ventas_g { get; set; }
        public decimal ventas_1 { get; set; }
        public decimal ventas_2 { get; set; }
        public decimal ventas_3 { get; set; }
        public decimal ventas_4 { get; set; }
        public decimal cobranza_g { get; set; }
        public decimal cobranza_1 { get; set; }
        public decimal cobranza_2 { get; set; }
        public decimal cobranza_3 { get; set; }
        public decimal cobranza_4 { get; set; }
        public string estatus_ventas { get; set; }
        public string estatus_cobranza { get; set; }
        public string estatus_departamento { get; set; }
        public string estatus_f1 { get; set; }
        public string estatus_f2 { get; set; }
        public string estatus_f3 { get; set; }
        public string estatus_f4 { get; set; }
        public string estatus_f5 { get; set; }
        public string estatus_f6 { get; set; }
        public string estatus_f7 { get; set; }
        public string estatus_f8 { get; set; }
        public decimal castigop { get; set; }
        public int tolerancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientes> clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cxc> cxc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_detalle> ventas_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
